version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile_local
    command: 'uvicorn main:app --host="0.0.0.0" --port=8000'
    restart: always
    env_file: .env

    ports:
      - "8000:8000"
